language: python
python:
  - "2.7"
  - "3.4"
install: 
  - "sudo apt-get install libcrypto++-dev"
  - "pip install coverage"
  - "pip install ."
script:
  - "cd tests/"
  - "nosetests -v --with-coverage --cover-package heartbeat"